import type { Metadata } from "next";
import "./globals.css";
import Layout from "./_components/features/Layout";

export const metadata: Metadata = {
  title: "Anime List with Kitsu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Layout>{children}</Layout>;
}
