import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "styled-components";
import { theme } from "./_styles/theme";
import Layout from "./_components/features/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Layout>{children}</Layout>;
}
